export type ButtonVariant = 'white'
    | 'secondary'
    | 'secondary-subtle'
    | 'secondary-selected'
    | 'danger'
    | 'danger-subtle'
    | 'auto-subtle'
    | 'auto-outline'
    | 'pistachio'
    | 'pistachio-outline'
    | 'pistachio-subtle'
    | 'midnight'
    | 'midnight-outline'
    | 'midnight-subtle'
    | 'turquoise'
    | 'turquoise-subtle';