export type ButtonVariant =
	| 'white'
	| 'muted'
	| 'muted-subtle'
	| 'muted-selected'
	| 'danger'
	| 'danger-subtle'
	| 'auto-subtle'
	| 'auto-outline'
	| 'secondary'
	| 'secondary-outline'
	| 'secondary-subtle'
	| 'primary'
	| 'primary-outline'
	| 'primary-subtle'
	| 'accent'
	| 'accent-subtle';
